### ISSUE TITLE
wait is causing in a quick test "Implicit use of 'self' in closure; use 'self.' to make capture semantics explicit"

### ISSUE THREAD

**Issue by dnsco** [groue/CombineExpectations#12]
Hey, I'm new to Swift, and trying to use this library. I've got a method that I'm trying to test on my repo class:

```Swift
func createActivity(name: String, uuid: UUID) -> AnyPublisher<Activity.ApiProxy, ApiError> {
```

in the tests I've got

```Swift
it("fetches activities") {
                let repo = RepoMan(email: "test@test.com", password: "password", moc: PersistenceController.preview.container.viewContext)

                let uname = "Hey Girl \(NSDate().timeIntervalSince1970)"
                let uuid = UUID()

                let activityPub = repo.createActivity(name: uname, uuid: uuid)
                let recorder = activityPub.record()
                let elements = try wait(for: recorder.elements, timeout: 3.0)
         // assertions on elements here
```

the wait line triggers the error

```
Implicit use of 'self' in closure; use 'self.' to make capture semantics explicit
```

I couldn't figure out what was going on, I realized that the closure context it might be referring to is the Quick test context ``` it() {}```

but I figured it doesn't hurt to ask in case you have a quick fix.

Thanks for the library and for taking your time to read this!

**Comment by dnsco** [comment]
I just got it to work an an XCTest and not a quick suite, so that appears to be the actual proble.

**Comment by groue** [comment]
Hello @dnsco. The `wait` method is not a free function; but a method of XCTestCase. The compiler requires an explicit `self` in some circumstances. You just met one, when `self` is captured by an "escaping closure". You might have to check your favorite Swift language guide about those. Meanwhile, follow the compiler advice, and insert `self` where required.
