### ISSUE TITLE
Cannot find 'XCTFail' in scope (Xcode 12.5)

### ISSUE THREAD

**Issue by chrisballinger** [groue/CombineExpectations#14]
I believe this is caused by a change in Xcode 12.5: https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-12_5-release-notes/

> Xcode no longer includes XCTest’s legacy Swift overlay library (libswiftXCTest.dylib). Use the library’s replacement, libXCTestSwiftSupport.dylib, instead. For frameworks that encounter build issues because of the removal of the legacy library, delete the framework and library search paths for libswiftXCTest.dylib and add the ENABLE_TESTING_SEARCH_PATHS=YES build setting. This setting automatically sets the target’s search paths so that it can locate the replacement XCTest library. (70365050)

I think resolving this may involve a minor podspec change to add the `ENABLE_TESTING_SEARCH_PATHS=YES` build setting, but I have not verified this yet. If that's the fix, I'm not sure if there's an equivalent fix available for `Package.swift` and SPM integrations.

**Comment by groue** [comment]
Hello @chrisballinger, I did not have the time to look at your issue yet.

Are you stuck, or did you find a workaround?

**Comment by chrisballinger** [comment]
Sorry haven't had time to dig deeper yet. Will be taking a closer look this week, hopefully it's just a quick fix.

**Comment by groue** [comment]
OK. I'll look at it as well. It's cool that you are not stuck in a bad position right now.

**Comment by chrisballinger** [comment]
@groue Finally got some time to look into it! PR here that fixes the issue: https://github.com/groue/CombineExpectations/pull/15
