### ISSUE TITLE
Using share() on publishers results in recorder to return nil

### ISSUE THREAD

**Issue by gtokman** [groue/CombineExpectations#18]
# Summary

Not sure if it's expected but running some tests, and whenever I'm using the `share()` operator, I get failing tests for the expected recorded result. Removing the operator fixes the test, but now I am no longer sharing the upstream result of the publisher.

# Example

```swift
// function being tested
let publisher = "hello".publisher.share()

publisher
.sink { ... } 

publisher.
 .sink { ... } 

// Test
let recorder = publisher.prefix(1).record()

let value = try wait(recorder.single, timeout: 0.3) // value is nil
```

**Comment by groue** [comment]
Hello @gtokman, thanks for the report, I'll have a look at it. Did you somehow investigate the issue already?

**Comment by edwinveger** [comment]
In your example, `"hello".publisher` is a cold publisher: it acts in response to a subscription. In this particular case, the publisher (see [docs](https://developer.apple.com/documentation/swift/sequence/3344717-publisher)) emits all its elements as Output in one go. And when "shielded" by the `share` operator, this publisher only receives one subscription (the one it gets from Publishers.Share), regardless of the amount of of Subscribers on `.share()`.

**Comment by groue** [comment]
Thank you @edwinveger for your explanation. Indeed there is nothing left to record after the shared publisher has been exhausted once.

@gtokman, you can witness the behavior of the shared publisher in a playground:

```swift
import Combine

// Prints:
// 1st subscription
// H
// i
// completed
// 2nd subscription
// completed

let publisher = "Hi".publisher.share()

print("1st subscription")
publisher
    .handleEvents(receiveCompletion: { _ in print("completed") })
    .sink { print($0 )}

print("2nd subscription")
publisher
    .handleEvents(receiveCompletion: { _ in print("completed") })
    .sink { print($0 )}
```

So CombineExpectations behaves as expected in this case. 

Maybe you are looking for a publisher that _replays_ previously published elements? This is a whole other question. You may want to check https://github.com/CombineCommunity/CombineExt, or Google, or StackOverflow.
