### ISSUE TITLE
Expect recorder to not emit a value

### ISSUE THREAD

**Issue by petrpavlik** [groue/CombineExpectations#19]
I'm trying to figure out the best way to cover a scenario where I expect a publisher to not to emit a value.

This does not work work because the internal XCTest expectation will mark the test as failed
```swift
receivedMessage = try? QuickSpec.current.wait(for: recorder.next(), timeout: 0.1)
```

The best solution I've found so far is to wrap the line in `XCTExpectFailure` as following
```swift
XCTExpectFailure("this should time out", options: XCTExpectedFailure.Options()) {
    receivedMessage = try? QuickSpec.current.wait(for: recorder.next(), timeout: 0.1)
 }
```

It still creates this gray "warning" I'd ideally like to get rid of, but I can live with it.
<img width="997" alt="Screenshot 2022-03-01 at 14 44 21" src="https://user-images.githubusercontent.com/1067678/156220946-d907a794-e842-485a-9d95-d42ea2e9249c.png">

Any opinions on this?

**Comment by groue** [comment]
Hello @petrpavlik,

Some expectations have an `inverted` modifier, and you may be well be after `next().inverted` of `prefix(1).inverted`.

**Comment by petrpavlik** [comment]
Ah, I did read through that but somehow missed this part. Thanks! closing this
