### ISSUE TITLE
Use @discardableResult

### ISSUE THREAD

**Issue by clausjoergensen** [groue/CombineExpectations#9]
It would be great if the wait(...) functions would be annotated with `@discardableResult`, removing the need for `_ =` in `_ = try wait(for:timeout:)`

**Comment by groue** [comment]
Hello @clausjoergensen.

I'm listening to your request, but I don't know what's behind. I would enjoy reading an explanation.

For example, why waiting for `last` if you don't care about the value? Shouldn't you wait for `finished` instead?

```swift
_ = try wait(for: recorder.last, timeout: ...)
try wait(for: recorder.finished, timeout: ...)
```

What do you think?

**Comment by clausjoergensen** [comment]
That implies you're working on a publisher that actually finishes. For instance recording a `@Published var list: [String]` will have a `last` value, but never finish. 

```
final class ViewModel: ObservableObject {
    @Published
    private(set) var strings: [String]
}

let viewModel = ViewModel()
let recorder = viewModel.$strings.record()
_ = try wait(for: recorder.next(), timeout: 1.0) // the recorder is not finished here.
```

**Comment by groue** [comment]
Sorry I did not answer earlier. `next` won't become `@discardableResult`, sorry.
